// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChampRemovedEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ChampRemovedEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ChampRemovedEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ChampRemovedEvent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ChampRemovedEvent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChampRemovedEvent_2eproto;
namespace Protocol {
class ChampionRemovedEvent;
struct ChampionRemovedEventDefaultTypeInternal;
extern ChampionRemovedEventDefaultTypeInternal _ChampionRemovedEvent_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ChampionRemovedEvent* Arena::CreateMaybeMessage<::Protocol::ChampionRemovedEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class ChampionRemovedEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ChampionRemovedEvent) */ {
 public:
  inline ChampionRemovedEvent() : ChampionRemovedEvent(nullptr) {}
  ~ChampionRemovedEvent() override;
  explicit PROTOBUF_CONSTEXPR ChampionRemovedEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChampionRemovedEvent(const ChampionRemovedEvent& from);
  ChampionRemovedEvent(ChampionRemovedEvent&& from) noexcept
    : ChampionRemovedEvent() {
    *this = ::std::move(from);
  }

  inline ChampionRemovedEvent& operator=(const ChampionRemovedEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChampionRemovedEvent& operator=(ChampionRemovedEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChampionRemovedEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChampionRemovedEvent* internal_default_instance() {
    return reinterpret_cast<const ChampionRemovedEvent*>(
               &_ChampionRemovedEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChampionRemovedEvent& a, ChampionRemovedEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(ChampionRemovedEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChampionRemovedEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChampionRemovedEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChampionRemovedEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChampionRemovedEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChampionRemovedEvent& from) {
    ChampionRemovedEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChampionRemovedEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ChampionRemovedEvent";
  }
  protected:
  explicit ChampionRemovedEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChampionUidFieldNumber = 1,
  };
  // repeated int32 championUid = 1;
  int championuid_size() const;
  private:
  int _internal_championuid_size() const;
  public:
  void clear_championuid();
  private:
  int32_t _internal_championuid(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_championuid() const;
  void _internal_add_championuid(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_championuid();
  public:
  int32_t championuid(int index) const;
  void set_championuid(int index, int32_t value);
  void add_championuid(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      championuid() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_championuid();

  // @@protoc_insertion_point(class_scope:Protocol.ChampionRemovedEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > championuid_;
    mutable std::atomic<int> _championuid_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ChampRemovedEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChampionRemovedEvent

// repeated int32 championUid = 1;
inline int ChampionRemovedEvent::_internal_championuid_size() const {
  return _impl_.championuid_.size();
}
inline int ChampionRemovedEvent::championuid_size() const {
  return _internal_championuid_size();
}
inline void ChampionRemovedEvent::clear_championuid() {
  _impl_.championuid_.Clear();
}
inline int32_t ChampionRemovedEvent::_internal_championuid(int index) const {
  return _impl_.championuid_.Get(index);
}
inline int32_t ChampionRemovedEvent::championuid(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.ChampionRemovedEvent.championUid)
  return _internal_championuid(index);
}
inline void ChampionRemovedEvent::set_championuid(int index, int32_t value) {
  _impl_.championuid_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.ChampionRemovedEvent.championUid)
}
inline void ChampionRemovedEvent::_internal_add_championuid(int32_t value) {
  _impl_.championuid_.Add(value);
}
inline void ChampionRemovedEvent::add_championuid(int32_t value) {
  _internal_add_championuid(value);
  // @@protoc_insertion_point(field_add:Protocol.ChampionRemovedEvent.championUid)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ChampionRemovedEvent::_internal_championuid() const {
  return _impl_.championuid_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ChampionRemovedEvent::championuid() const {
  // @@protoc_insertion_point(field_list:Protocol.ChampionRemovedEvent.championUid)
  return _internal_championuid();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ChampionRemovedEvent::_internal_mutable_championuid() {
  return &_impl_.championuid_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ChampionRemovedEvent::mutable_championuid() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.ChampionRemovedEvent.championUid)
  return _internal_mutable_championuid();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ChampRemovedEvent_2eproto
