// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChampCreatedEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ChampCreatedEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ChampCreatedEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ChampStat.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ChampCreatedEvent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ChampCreatedEvent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChampCreatedEvent_2eproto;
namespace Protocol {
class ChampionCreatedEvent;
struct ChampionCreatedEventDefaultTypeInternal;
extern ChampionCreatedEventDefaultTypeInternal _ChampionCreatedEvent_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ChampionCreatedEvent* Arena::CreateMaybeMessage<::Protocol::ChampionCreatedEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class ChampionCreatedEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ChampionCreatedEvent) */ {
 public:
  inline ChampionCreatedEvent() : ChampionCreatedEvent(nullptr) {}
  ~ChampionCreatedEvent() override;
  explicit PROTOBUF_CONSTEXPR ChampionCreatedEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChampionCreatedEvent(const ChampionCreatedEvent& from);
  ChampionCreatedEvent(ChampionCreatedEvent&& from) noexcept
    : ChampionCreatedEvent() {
    *this = ::std::move(from);
  }

  inline ChampionCreatedEvent& operator=(const ChampionCreatedEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChampionCreatedEvent& operator=(ChampionCreatedEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChampionCreatedEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChampionCreatedEvent* internal_default_instance() {
    return reinterpret_cast<const ChampionCreatedEvent*>(
               &_ChampionCreatedEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChampionCreatedEvent& a, ChampionCreatedEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(ChampionCreatedEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChampionCreatedEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChampionCreatedEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChampionCreatedEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChampionCreatedEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChampionCreatedEvent& from) {
    ChampionCreatedEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChampionCreatedEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ChampionCreatedEvent";
  }
  protected:
  explicit ChampionCreatedEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatFieldNumber = 2,
    kChampionUidFieldNumber = 1,
  };
  // .Protocol.ChampStat stat = 2;
  bool has_stat() const;
  private:
  bool _internal_has_stat() const;
  public:
  void clear_stat();
  const ::Protocol::ChampStat& stat() const;
  PROTOBUF_NODISCARD ::Protocol::ChampStat* release_stat();
  ::Protocol::ChampStat* mutable_stat();
  void set_allocated_stat(::Protocol::ChampStat* stat);
  private:
  const ::Protocol::ChampStat& _internal_stat() const;
  ::Protocol::ChampStat* _internal_mutable_stat();
  public:
  void unsafe_arena_set_allocated_stat(
      ::Protocol::ChampStat* stat);
  ::Protocol::ChampStat* unsafe_arena_release_stat();

  // int32 championUid = 1;
  void clear_championuid();
  int32_t championuid() const;
  void set_championuid(int32_t value);
  private:
  int32_t _internal_championuid() const;
  void _internal_set_championuid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ChampionCreatedEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::ChampStat* stat_;
    int32_t championuid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ChampCreatedEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChampionCreatedEvent

// int32 championUid = 1;
inline void ChampionCreatedEvent::clear_championuid() {
  _impl_.championuid_ = 0;
}
inline int32_t ChampionCreatedEvent::_internal_championuid() const {
  return _impl_.championuid_;
}
inline int32_t ChampionCreatedEvent::championuid() const {
  // @@protoc_insertion_point(field_get:Protocol.ChampionCreatedEvent.championUid)
  return _internal_championuid();
}
inline void ChampionCreatedEvent::_internal_set_championuid(int32_t value) {
  
  _impl_.championuid_ = value;
}
inline void ChampionCreatedEvent::set_championuid(int32_t value) {
  _internal_set_championuid(value);
  // @@protoc_insertion_point(field_set:Protocol.ChampionCreatedEvent.championUid)
}

// .Protocol.ChampStat stat = 2;
inline bool ChampionCreatedEvent::_internal_has_stat() const {
  return this != internal_default_instance() && _impl_.stat_ != nullptr;
}
inline bool ChampionCreatedEvent::has_stat() const {
  return _internal_has_stat();
}
inline const ::Protocol::ChampStat& ChampionCreatedEvent::_internal_stat() const {
  const ::Protocol::ChampStat* p = _impl_.stat_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::ChampStat&>(
      ::Protocol::_ChampStat_default_instance_);
}
inline const ::Protocol::ChampStat& ChampionCreatedEvent::stat() const {
  // @@protoc_insertion_point(field_get:Protocol.ChampionCreatedEvent.stat)
  return _internal_stat();
}
inline void ChampionCreatedEvent::unsafe_arena_set_allocated_stat(
    ::Protocol::ChampStat* stat) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stat_);
  }
  _impl_.stat_ = stat;
  if (stat) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ChampionCreatedEvent.stat)
}
inline ::Protocol::ChampStat* ChampionCreatedEvent::release_stat() {
  
  ::Protocol::ChampStat* temp = _impl_.stat_;
  _impl_.stat_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::ChampStat* ChampionCreatedEvent::unsafe_arena_release_stat() {
  // @@protoc_insertion_point(field_release:Protocol.ChampionCreatedEvent.stat)
  
  ::Protocol::ChampStat* temp = _impl_.stat_;
  _impl_.stat_ = nullptr;
  return temp;
}
inline ::Protocol::ChampStat* ChampionCreatedEvent::_internal_mutable_stat() {
  
  if (_impl_.stat_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::ChampStat>(GetArenaForAllocation());
    _impl_.stat_ = p;
  }
  return _impl_.stat_;
}
inline ::Protocol::ChampStat* ChampionCreatedEvent::mutable_stat() {
  ::Protocol::ChampStat* _msg = _internal_mutable_stat();
  // @@protoc_insertion_point(field_mutable:Protocol.ChampionCreatedEvent.stat)
  return _msg;
}
inline void ChampionCreatedEvent::set_allocated_stat(::Protocol::ChampStat* stat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stat_);
  }
  if (stat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stat));
    if (message_arena != submessage_arena) {
      stat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stat, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stat_ = stat;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ChampionCreatedEvent.stat)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ChampCreatedEvent_2eproto
