// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChampCreatedEvent.proto

#include "ChampCreatedEvent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR ChampionCreatedEvent::ChampionCreatedEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stat_)*/nullptr
  , /*decltype(_impl_.championuid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChampionCreatedEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChampionCreatedEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChampionCreatedEventDefaultTypeInternal() {}
  union {
    ChampionCreatedEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChampionCreatedEventDefaultTypeInternal _ChampionCreatedEvent_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_ChampCreatedEvent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ChampCreatedEvent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ChampCreatedEvent_2eproto = nullptr;

const uint32_t TableStruct_ChampCreatedEvent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::ChampionCreatedEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::ChampionCreatedEvent, _impl_.championuid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::ChampionCreatedEvent, _impl_.stat_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::ChampionCreatedEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_ChampionCreatedEvent_default_instance_._instance,
};

const char descriptor_table_protodef_ChampCreatedEvent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027ChampCreatedEvent.proto\022\010Protocol\032\017Cha"
  "mpStat.proto\"N\n\024ChampionCreatedEvent\022\023\n\013"
  "championUid\030\001 \001(\005\022!\n\004stat\030\002 \001(\0132\023.Protoc"
  "ol.ChampStatb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ChampCreatedEvent_2eproto_deps[1] = {
  &::descriptor_table_ChampStat_2eproto,
};
static ::_pbi::once_flag descriptor_table_ChampCreatedEvent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ChampCreatedEvent_2eproto = {
    false, false, 140, descriptor_table_protodef_ChampCreatedEvent_2eproto,
    "ChampCreatedEvent.proto",
    &descriptor_table_ChampCreatedEvent_2eproto_once, descriptor_table_ChampCreatedEvent_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_ChampCreatedEvent_2eproto::offsets,
    file_level_metadata_ChampCreatedEvent_2eproto, file_level_enum_descriptors_ChampCreatedEvent_2eproto,
    file_level_service_descriptors_ChampCreatedEvent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ChampCreatedEvent_2eproto_getter() {
  return &descriptor_table_ChampCreatedEvent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ChampCreatedEvent_2eproto(&descriptor_table_ChampCreatedEvent_2eproto);
namespace Protocol {

// ===================================================================

class ChampionCreatedEvent::_Internal {
 public:
  static const ::Protocol::ChampStat& stat(const ChampionCreatedEvent* msg);
};

const ::Protocol::ChampStat&
ChampionCreatedEvent::_Internal::stat(const ChampionCreatedEvent* msg) {
  return *msg->_impl_.stat_;
}
void ChampionCreatedEvent::clear_stat() {
  if (GetArenaForAllocation() == nullptr && _impl_.stat_ != nullptr) {
    delete _impl_.stat_;
  }
  _impl_.stat_ = nullptr;
}
ChampionCreatedEvent::ChampionCreatedEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.ChampionCreatedEvent)
}
ChampionCreatedEvent::ChampionCreatedEvent(const ChampionCreatedEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChampionCreatedEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stat_){nullptr}
    , decltype(_impl_.championuid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_stat()) {
    _this->_impl_.stat_ = new ::Protocol::ChampStat(*from._impl_.stat_);
  }
  _this->_impl_.championuid_ = from._impl_.championuid_;
  // @@protoc_insertion_point(copy_constructor:Protocol.ChampionCreatedEvent)
}

inline void ChampionCreatedEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stat_){nullptr}
    , decltype(_impl_.championuid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChampionCreatedEvent::~ChampionCreatedEvent() {
  // @@protoc_insertion_point(destructor:Protocol.ChampionCreatedEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChampionCreatedEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.stat_;
}

void ChampionCreatedEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChampionCreatedEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ChampionCreatedEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.stat_ != nullptr) {
    delete _impl_.stat_;
  }
  _impl_.stat_ = nullptr;
  _impl_.championuid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChampionCreatedEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 championUid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.championuid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.ChampStat stat = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_stat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChampionCreatedEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ChampionCreatedEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 championUid = 1;
  if (this->_internal_championuid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_championuid(), target);
  }

  // .Protocol.ChampStat stat = 2;
  if (this->_internal_has_stat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::stat(this),
        _Internal::stat(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ChampionCreatedEvent)
  return target;
}

size_t ChampionCreatedEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ChampionCreatedEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.ChampStat stat = 2;
  if (this->_internal_has_stat()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.stat_);
  }

  // int32 championUid = 1;
  if (this->_internal_championuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_championuid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChampionCreatedEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChampionCreatedEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChampionCreatedEvent::GetClassData() const { return &_class_data_; }


void ChampionCreatedEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChampionCreatedEvent*>(&to_msg);
  auto& from = static_cast<const ChampionCreatedEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ChampionCreatedEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_stat()) {
    _this->_internal_mutable_stat()->::Protocol::ChampStat::MergeFrom(
        from._internal_stat());
  }
  if (from._internal_championuid() != 0) {
    _this->_internal_set_championuid(from._internal_championuid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChampionCreatedEvent::CopyFrom(const ChampionCreatedEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ChampionCreatedEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChampionCreatedEvent::IsInitialized() const {
  return true;
}

void ChampionCreatedEvent::InternalSwap(ChampionCreatedEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChampionCreatedEvent, _impl_.championuid_)
      + sizeof(ChampionCreatedEvent::_impl_.championuid_)
      - PROTOBUF_FIELD_OFFSET(ChampionCreatedEvent, _impl_.stat_)>(
          reinterpret_cast<char*>(&_impl_.stat_),
          reinterpret_cast<char*>(&other->_impl_.stat_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChampionCreatedEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ChampCreatedEvent_2eproto_getter, &descriptor_table_ChampCreatedEvent_2eproto_once,
      file_level_metadata_ChampCreatedEvent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::ChampionCreatedEvent*
Arena::CreateMaybeMessage< ::Protocol::ChampionCreatedEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::ChampionCreatedEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
