// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChampRemovedEvent.proto

#include "ChampRemovedEvent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR ChampionRemovedEvent::ChampionRemovedEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.championuid_)*/{}
  , /*decltype(_impl_._championuid_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChampionRemovedEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChampionRemovedEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChampionRemovedEventDefaultTypeInternal() {}
  union {
    ChampionRemovedEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChampionRemovedEventDefaultTypeInternal _ChampionRemovedEvent_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_ChampRemovedEvent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ChampRemovedEvent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ChampRemovedEvent_2eproto = nullptr;

const uint32_t TableStruct_ChampRemovedEvent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::ChampionRemovedEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::ChampionRemovedEvent, _impl_.championuid_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::ChampionRemovedEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_ChampionRemovedEvent_default_instance_._instance,
};

const char descriptor_table_protodef_ChampRemovedEvent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027ChampRemovedEvent.proto\022\010Protocol\"+\n\024C"
  "hampionRemovedEvent\022\023\n\013championUid\030\001 \003(\005"
  "b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ChampRemovedEvent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ChampRemovedEvent_2eproto = {
    false, false, 88, descriptor_table_protodef_ChampRemovedEvent_2eproto,
    "ChampRemovedEvent.proto",
    &descriptor_table_ChampRemovedEvent_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ChampRemovedEvent_2eproto::offsets,
    file_level_metadata_ChampRemovedEvent_2eproto, file_level_enum_descriptors_ChampRemovedEvent_2eproto,
    file_level_service_descriptors_ChampRemovedEvent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ChampRemovedEvent_2eproto_getter() {
  return &descriptor_table_ChampRemovedEvent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ChampRemovedEvent_2eproto(&descriptor_table_ChampRemovedEvent_2eproto);
namespace Protocol {

// ===================================================================

class ChampionRemovedEvent::_Internal {
 public:
};

ChampionRemovedEvent::ChampionRemovedEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.ChampionRemovedEvent)
}
ChampionRemovedEvent::ChampionRemovedEvent(const ChampionRemovedEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChampionRemovedEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.championuid_){from._impl_.championuid_}
    , /*decltype(_impl_._championuid_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.ChampionRemovedEvent)
}

inline void ChampionRemovedEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.championuid_){arena}
    , /*decltype(_impl_._championuid_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChampionRemovedEvent::~ChampionRemovedEvent() {
  // @@protoc_insertion_point(destructor:Protocol.ChampionRemovedEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChampionRemovedEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.championuid_.~RepeatedField();
}

void ChampionRemovedEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChampionRemovedEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ChampionRemovedEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.championuid_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChampionRemovedEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 championUid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_championuid(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_championuid(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChampionRemovedEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ChampionRemovedEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 championUid = 1;
  {
    int byte_size = _impl_._championuid_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_championuid(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ChampionRemovedEvent)
  return target;
}

size_t ChampionRemovedEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ChampionRemovedEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 championUid = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.championuid_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._championuid_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChampionRemovedEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChampionRemovedEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChampionRemovedEvent::GetClassData() const { return &_class_data_; }


void ChampionRemovedEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChampionRemovedEvent*>(&to_msg);
  auto& from = static_cast<const ChampionRemovedEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ChampionRemovedEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.championuid_.MergeFrom(from._impl_.championuid_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChampionRemovedEvent::CopyFrom(const ChampionRemovedEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ChampionRemovedEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChampionRemovedEvent::IsInitialized() const {
  return true;
}

void ChampionRemovedEvent::InternalSwap(ChampionRemovedEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.championuid_.InternalSwap(&other->_impl_.championuid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChampionRemovedEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ChampRemovedEvent_2eproto_getter, &descriptor_table_ChampRemovedEvent_2eproto_once,
      file_level_metadata_ChampRemovedEvent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::ChampionRemovedEvent*
Arena::CreateMaybeMessage< ::Protocol::ChampionRemovedEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::ChampionRemovedEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
