// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateHostRequest.proto

#include "CreateHostRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR CreateHostRequest::CreateHostRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playerid_)*/{}
  , /*decltype(_impl_._playerid_cached_byte_size_)*/{0}
  , /*decltype(_impl_.matchid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateHostRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateHostRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateHostRequestDefaultTypeInternal() {}
  union {
    CreateHostRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateHostRequestDefaultTypeInternal _CreateHostRequest_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_CreateHostRequest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_CreateHostRequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_CreateHostRequest_2eproto = nullptr;

const uint32_t TableStruct_CreateHostRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CreateHostRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CreateHostRequest, _impl_.matchid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CreateHostRequest, _impl_.playerid_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::CreateHostRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_CreateHostRequest_default_instance_._instance,
};

const char descriptor_table_protodef_CreateHostRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027CreateHostRequest.proto\022\010Protocol\"6\n\021C"
  "reateHostRequest\022\017\n\007matchId\030\001 \001(\005\022\020\n\010pla"
  "yerId\030\002 \003(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_CreateHostRequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_CreateHostRequest_2eproto = {
    false, false, 99, descriptor_table_protodef_CreateHostRequest_2eproto,
    "CreateHostRequest.proto",
    &descriptor_table_CreateHostRequest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_CreateHostRequest_2eproto::offsets,
    file_level_metadata_CreateHostRequest_2eproto, file_level_enum_descriptors_CreateHostRequest_2eproto,
    file_level_service_descriptors_CreateHostRequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_CreateHostRequest_2eproto_getter() {
  return &descriptor_table_CreateHostRequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_CreateHostRequest_2eproto(&descriptor_table_CreateHostRequest_2eproto);
namespace Protocol {

// ===================================================================

class CreateHostRequest::_Internal {
 public:
};

CreateHostRequest::CreateHostRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CreateHostRequest)
}
CreateHostRequest::CreateHostRequest(const CreateHostRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateHostRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){from._impl_.playerid_}
    , /*decltype(_impl_._playerid_cached_byte_size_)*/{0}
    , decltype(_impl_.matchid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.matchid_ = from._impl_.matchid_;
  // @@protoc_insertion_point(copy_constructor:Protocol.CreateHostRequest)
}

inline void CreateHostRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){arena}
    , /*decltype(_impl_._playerid_cached_byte_size_)*/{0}
    , decltype(_impl_.matchid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CreateHostRequest::~CreateHostRequest() {
  // @@protoc_insertion_point(destructor:Protocol.CreateHostRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateHostRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.playerid_.~RepeatedField();
}

void CreateHostRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateHostRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CreateHostRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playerid_.Clear();
  _impl_.matchid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateHostRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 matchId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.matchid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 playerId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_playerid(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_playerid(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateHostRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CreateHostRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 matchId = 1;
  if (this->_internal_matchid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_matchid(), target);
  }

  // repeated int32 playerId = 2;
  {
    int byte_size = _impl_._playerid_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_playerid(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CreateHostRequest)
  return target;
}

size_t CreateHostRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CreateHostRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 playerId = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.playerid_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._playerid_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int32 matchId = 1;
  if (this->_internal_matchid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_matchid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateHostRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateHostRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateHostRequest::GetClassData() const { return &_class_data_; }


void CreateHostRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateHostRequest*>(&to_msg);
  auto& from = static_cast<const CreateHostRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CreateHostRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.playerid_.MergeFrom(from._impl_.playerid_);
  if (from._internal_matchid() != 0) {
    _this->_internal_set_matchid(from._internal_matchid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateHostRequest::CopyFrom(const CreateHostRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CreateHostRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateHostRequest::IsInitialized() const {
  return true;
}

void CreateHostRequest::InternalSwap(CreateHostRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.playerid_.InternalSwap(&other->_impl_.playerid_);
  swap(_impl_.matchid_, other->_impl_.matchid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateHostRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CreateHostRequest_2eproto_getter, &descriptor_table_CreateHostRequest_2eproto_once,
      file_level_metadata_CreateHostRequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::CreateHostRequest*
Arena::CreateMaybeMessage< ::Protocol::CreateHostRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CreateHostRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
