// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HostCreateRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HostCreateRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HostCreateRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HostCreateRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HostCreateRequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HostCreateRequest_2eproto;
namespace Protocol {
class HostCreateRequest;
struct HostCreateRequestDefaultTypeInternal;
extern HostCreateRequestDefaultTypeInternal _HostCreateRequest_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::HostCreateRequest* Arena::CreateMaybeMessage<::Protocol::HostCreateRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class HostCreateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.HostCreateRequest) */ {
 public:
  inline HostCreateRequest() : HostCreateRequest(nullptr) {}
  ~HostCreateRequest() override;
  explicit PROTOBUF_CONSTEXPR HostCreateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HostCreateRequest(const HostCreateRequest& from);
  HostCreateRequest(HostCreateRequest&& from) noexcept
    : HostCreateRequest() {
    *this = ::std::move(from);
  }

  inline HostCreateRequest& operator=(const HostCreateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostCreateRequest& operator=(HostCreateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HostCreateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HostCreateRequest* internal_default_instance() {
    return reinterpret_cast<const HostCreateRequest*>(
               &_HostCreateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HostCreateRequest& a, HostCreateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HostCreateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HostCreateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HostCreateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HostCreateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HostCreateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HostCreateRequest& from) {
    HostCreateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HostCreateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.HostCreateRequest";
  }
  protected:
  explicit HostCreateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 2,
    kMatchIdFieldNumber = 1,
  };
  // repeated int32 playerId = 2;
  int playerid_size() const;
  private:
  int _internal_playerid_size() const;
  public:
  void clear_playerid();
  private:
  int32_t _internal_playerid(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_playerid() const;
  void _internal_add_playerid(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_playerid();
  public:
  int32_t playerid(int index) const;
  void set_playerid(int index, int32_t value);
  void add_playerid(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      playerid() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_playerid();

  // int32 matchId = 1;
  void clear_matchid();
  int32_t matchid() const;
  void set_matchid(int32_t value);
  private:
  int32_t _internal_matchid() const;
  void _internal_set_matchid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.HostCreateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > playerid_;
    mutable std::atomic<int> _playerid_cached_byte_size_;
    int32_t matchid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HostCreateRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HostCreateRequest

// int32 matchId = 1;
inline void HostCreateRequest::clear_matchid() {
  _impl_.matchid_ = 0;
}
inline int32_t HostCreateRequest::_internal_matchid() const {
  return _impl_.matchid_;
}
inline int32_t HostCreateRequest::matchid() const {
  // @@protoc_insertion_point(field_get:Protocol.HostCreateRequest.matchId)
  return _internal_matchid();
}
inline void HostCreateRequest::_internal_set_matchid(int32_t value) {
  
  _impl_.matchid_ = value;
}
inline void HostCreateRequest::set_matchid(int32_t value) {
  _internal_set_matchid(value);
  // @@protoc_insertion_point(field_set:Protocol.HostCreateRequest.matchId)
}

// repeated int32 playerId = 2;
inline int HostCreateRequest::_internal_playerid_size() const {
  return _impl_.playerid_.size();
}
inline int HostCreateRequest::playerid_size() const {
  return _internal_playerid_size();
}
inline void HostCreateRequest::clear_playerid() {
  _impl_.playerid_.Clear();
}
inline int32_t HostCreateRequest::_internal_playerid(int index) const {
  return _impl_.playerid_.Get(index);
}
inline int32_t HostCreateRequest::playerid(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.HostCreateRequest.playerId)
  return _internal_playerid(index);
}
inline void HostCreateRequest::set_playerid(int index, int32_t value) {
  _impl_.playerid_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.HostCreateRequest.playerId)
}
inline void HostCreateRequest::_internal_add_playerid(int32_t value) {
  _impl_.playerid_.Add(value);
}
inline void HostCreateRequest::add_playerid(int32_t value) {
  _internal_add_playerid(value);
  // @@protoc_insertion_point(field_add:Protocol.HostCreateRequest.playerId)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
HostCreateRequest::_internal_playerid() const {
  return _impl_.playerid_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
HostCreateRequest::playerid() const {
  // @@protoc_insertion_point(field_list:Protocol.HostCreateRequest.playerId)
  return _internal_playerid();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
HostCreateRequest::_internal_mutable_playerid() {
  return &_impl_.playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
HostCreateRequest::mutable_playerid() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.HostCreateRequest.playerId)
  return _internal_mutable_playerid();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HostCreateRequest_2eproto
