// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocatedOnFieldEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_LocatedOnFieldEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_LocatedOnFieldEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_LocatedOnFieldEvent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_LocatedOnFieldEvent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LocatedOnFieldEvent_2eproto;
namespace Protocol {
class LocatedOnField;
struct LocatedOnFieldDefaultTypeInternal;
extern LocatedOnFieldDefaultTypeInternal _LocatedOnField_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::LocatedOnField* Arena::CreateMaybeMessage<::Protocol::LocatedOnField>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class LocatedOnField final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.LocatedOnField) */ {
 public:
  inline LocatedOnField() : LocatedOnField(nullptr) {}
  ~LocatedOnField() override;
  explicit PROTOBUF_CONSTEXPR LocatedOnField(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LocatedOnField(const LocatedOnField& from);
  LocatedOnField(LocatedOnField&& from) noexcept
    : LocatedOnField() {
    *this = ::std::move(from);
  }

  inline LocatedOnField& operator=(const LocatedOnField& from) {
    CopyFrom(from);
    return *this;
  }
  inline LocatedOnField& operator=(LocatedOnField&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LocatedOnField& default_instance() {
    return *internal_default_instance();
  }
  static inline const LocatedOnField* internal_default_instance() {
    return reinterpret_cast<const LocatedOnField*>(
               &_LocatedOnField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LocatedOnField& a, LocatedOnField& b) {
    a.Swap(&b);
  }
  inline void Swap(LocatedOnField* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LocatedOnField* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LocatedOnField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LocatedOnField>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LocatedOnField& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LocatedOnField& from) {
    LocatedOnField::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LocatedOnField* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.LocatedOnField";
  }
  protected:
  explicit LocatedOnField(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChampionUidFieldNumber = 1,
    kFieldIndexFieldNumber = 2,
  };
  // int32 championUid = 1;
  void clear_championuid();
  int32_t championuid() const;
  void set_championuid(int32_t value);
  private:
  int32_t _internal_championuid() const;
  void _internal_set_championuid(int32_t value);
  public:

  // int32 fieldIndex = 2;
  void clear_fieldindex();
  int32_t fieldindex() const;
  void set_fieldindex(int32_t value);
  private:
  int32_t _internal_fieldindex() const;
  void _internal_set_fieldindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.LocatedOnField)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t championuid_;
    int32_t fieldindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LocatedOnFieldEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LocatedOnField

// int32 championUid = 1;
inline void LocatedOnField::clear_championuid() {
  _impl_.championuid_ = 0;
}
inline int32_t LocatedOnField::_internal_championuid() const {
  return _impl_.championuid_;
}
inline int32_t LocatedOnField::championuid() const {
  // @@protoc_insertion_point(field_get:Protocol.LocatedOnField.championUid)
  return _internal_championuid();
}
inline void LocatedOnField::_internal_set_championuid(int32_t value) {
  
  _impl_.championuid_ = value;
}
inline void LocatedOnField::set_championuid(int32_t value) {
  _internal_set_championuid(value);
  // @@protoc_insertion_point(field_set:Protocol.LocatedOnField.championUid)
}

// int32 fieldIndex = 2;
inline void LocatedOnField::clear_fieldindex() {
  _impl_.fieldindex_ = 0;
}
inline int32_t LocatedOnField::_internal_fieldindex() const {
  return _impl_.fieldindex_;
}
inline int32_t LocatedOnField::fieldindex() const {
  // @@protoc_insertion_point(field_get:Protocol.LocatedOnField.fieldIndex)
  return _internal_fieldindex();
}
inline void LocatedOnField::_internal_set_fieldindex(int32_t value) {
  
  _impl_.fieldindex_ = value;
}
inline void LocatedOnField::set_fieldindex(int32_t value) {
  _internal_set_fieldindex(value);
  // @@protoc_insertion_point(field_set:Protocol.LocatedOnField.fieldIndex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_LocatedOnFieldEvent_2eproto
