// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatchCreatedSend.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MatchCreatedSend_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MatchCreatedSend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MatchCreatedSend_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MatchCreatedSend_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MatchCreatedSend_2eproto;
namespace Protocol {
class MatchCreatedSend;
struct MatchCreatedSendDefaultTypeInternal;
extern MatchCreatedSendDefaultTypeInternal _MatchCreatedSend_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::MatchCreatedSend* Arena::CreateMaybeMessage<::Protocol::MatchCreatedSend>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class MatchCreatedSend final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.MatchCreatedSend) */ {
 public:
  inline MatchCreatedSend() : MatchCreatedSend(nullptr) {}
  ~MatchCreatedSend() override;
  explicit PROTOBUF_CONSTEXPR MatchCreatedSend(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatchCreatedSend(const MatchCreatedSend& from);
  MatchCreatedSend(MatchCreatedSend&& from) noexcept
    : MatchCreatedSend() {
    *this = ::std::move(from);
  }

  inline MatchCreatedSend& operator=(const MatchCreatedSend& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchCreatedSend& operator=(MatchCreatedSend&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchCreatedSend& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchCreatedSend* internal_default_instance() {
    return reinterpret_cast<const MatchCreatedSend*>(
               &_MatchCreatedSend_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MatchCreatedSend& a, MatchCreatedSend& b) {
    a.Swap(&b);
  }
  inline void Swap(MatchCreatedSend* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchCreatedSend* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchCreatedSend* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatchCreatedSend>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatchCreatedSend& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatchCreatedSend& from) {
    MatchCreatedSend::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatchCreatedSend* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.MatchCreatedSend";
  }
  protected:
  explicit MatchCreatedSend(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 3,
    kResultFieldNumber = 1,
    kPlayerIdFieldNumber = 2,
    kPortFieldNumber = 4,
  };
  // string address = 3;
  void clear_address();
  const std::string& address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_address();
  PROTOBUF_NODISCARD std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // bool result = 1;
  void clear_result();
  bool result() const;
  void set_result(bool value);
  private:
  bool _internal_result() const;
  void _internal_set_result(bool value);
  public:

  // int32 playerId = 2;
  void clear_playerid();
  int32_t playerid() const;
  void set_playerid(int32_t value);
  private:
  int32_t _internal_playerid() const;
  void _internal_set_playerid(int32_t value);
  public:

  // int32 port = 4;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.MatchCreatedSend)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
    bool result_;
    int32_t playerid_;
    int32_t port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MatchCreatedSend_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MatchCreatedSend

// bool result = 1;
inline void MatchCreatedSend::clear_result() {
  _impl_.result_ = false;
}
inline bool MatchCreatedSend::_internal_result() const {
  return _impl_.result_;
}
inline bool MatchCreatedSend::result() const {
  // @@protoc_insertion_point(field_get:Protocol.MatchCreatedSend.result)
  return _internal_result();
}
inline void MatchCreatedSend::_internal_set_result(bool value) {
  
  _impl_.result_ = value;
}
inline void MatchCreatedSend::set_result(bool value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.MatchCreatedSend.result)
}

// int32 playerId = 2;
inline void MatchCreatedSend::clear_playerid() {
  _impl_.playerid_ = 0;
}
inline int32_t MatchCreatedSend::_internal_playerid() const {
  return _impl_.playerid_;
}
inline int32_t MatchCreatedSend::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.MatchCreatedSend.playerId)
  return _internal_playerid();
}
inline void MatchCreatedSend::_internal_set_playerid(int32_t value) {
  
  _impl_.playerid_ = value;
}
inline void MatchCreatedSend::set_playerid(int32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.MatchCreatedSend.playerId)
}

// string address = 3;
inline void MatchCreatedSend::clear_address() {
  _impl_.address_.ClearToEmpty();
}
inline const std::string& MatchCreatedSend::address() const {
  // @@protoc_insertion_point(field_get:Protocol.MatchCreatedSend.address)
  return _internal_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MatchCreatedSend::set_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.MatchCreatedSend.address)
}
inline std::string* MatchCreatedSend::mutable_address() {
  std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:Protocol.MatchCreatedSend.address)
  return _s;
}
inline const std::string& MatchCreatedSend::_internal_address() const {
  return _impl_.address_.Get();
}
inline void MatchCreatedSend::_internal_set_address(const std::string& value) {
  
  _impl_.address_.Set(value, GetArenaForAllocation());
}
inline std::string* MatchCreatedSend::_internal_mutable_address() {
  
  return _impl_.address_.Mutable(GetArenaForAllocation());
}
inline std::string* MatchCreatedSend::release_address() {
  // @@protoc_insertion_point(field_release:Protocol.MatchCreatedSend.address)
  return _impl_.address_.Release();
}
inline void MatchCreatedSend::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  _impl_.address_.SetAllocated(address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.address_.IsDefault()) {
    _impl_.address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.MatchCreatedSend.address)
}

// int32 port = 4;
inline void MatchCreatedSend::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t MatchCreatedSend::_internal_port() const {
  return _impl_.port_;
}
inline int32_t MatchCreatedSend::port() const {
  // @@protoc_insertion_point(field_get:Protocol.MatchCreatedSend.port)
  return _internal_port();
}
inline void MatchCreatedSend::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void MatchCreatedSend::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:Protocol.MatchCreatedSend.port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MatchCreatedSend_2eproto
