// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatchRequest.proto

#include "MatchRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR MatchRequest::MatchRequest(
    ::_pbi::ConstantInitialized) {}
struct MatchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatchRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatchRequestDefaultTypeInternal() {}
  union {
    MatchRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatchRequestDefaultTypeInternal _MatchRequest_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_MatchRequest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_MatchRequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MatchRequest_2eproto = nullptr;

const uint32_t TableStruct_MatchRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::MatchRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::MatchRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_MatchRequest_default_instance_._instance,
};

const char descriptor_table_protodef_MatchRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022MatchRequest.proto\022\010Protocol\"\016\n\014MatchR"
  "equestb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MatchRequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MatchRequest_2eproto = {
    false, false, 54, descriptor_table_protodef_MatchRequest_2eproto,
    "MatchRequest.proto",
    &descriptor_table_MatchRequest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_MatchRequest_2eproto::offsets,
    file_level_metadata_MatchRequest_2eproto, file_level_enum_descriptors_MatchRequest_2eproto,
    file_level_service_descriptors_MatchRequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MatchRequest_2eproto_getter() {
  return &descriptor_table_MatchRequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MatchRequest_2eproto(&descriptor_table_MatchRequest_2eproto);
namespace Protocol {

// ===================================================================

class MatchRequest::_Internal {
 public:
};

MatchRequest::MatchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.MatchRequest)
}
MatchRequest::MatchRequest(const MatchRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MatchRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.MatchRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatchRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatchRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MatchRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MatchRequest_2eproto_getter, &descriptor_table_MatchRequest_2eproto_once,
      file_level_metadata_MatchRequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::MatchRequest*
Arena::CreateMaybeMessage< ::Protocol::MatchRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::MatchRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
